Algoritmo "Entrada e Saída e Dados"

// Descrição   : Entrada e Saída de Dados
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/06/2021
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite seu nome:")
   leia (nome)
   escreval("Digite sua nota:")
   leia(nota)
   
   escreval("O nome digitado foi:", nome)
   escreval("A nota digitada foi:", nota)
Fimalgoritmo